-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le :  mar. 14 jan. 2020 à 21:28
-- Version du serveur :  10.4.10-MariaDB
-- Version de PHP :  7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `rezo`
--
CREATE DATABASE IF NOT EXISTS `rezo` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `rezo`;

-- --------------------------------------------------------

--
-- Structure de la table `codes`
--

DROP TABLE IF EXISTS `codes`;
CREATE TABLE IF NOT EXISTS `codes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` longtext DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;

--
-- Déchargement des données de la table `codes`
--

INSERT INTO `codes` (`id`, `code`) VALUES
(1, 'if (!empty($_GET[\'id\']) && $_GET[\'id\'] === get_session(\'user_id\')) {\r\n    //recuperer les infos d\'user en bdd\r\n    $user = find_user_by_id($_GET[\'id\']);\r\n\r\n    if (!$user) {\r\n        redirect(\'index.php\');\r\n    }\r\n} else {\r\n    redirect(\'profile.php?id=\' . get_session(\'user_id\'));\r\n}\r\n\r\nif (isset($_POST[\'update\'])) {\r\n    //Si tous les champs ont Ã©tÃ© complÃ©tÃ©s\r\n    if (not_empty([\'name\', \'city\', \'country\', \'sex\', \'bio\'])) {\r\n        $errors = [];\r\n\r\n        extract($_POST);\r\n\r\n        //mise Ã  jour du profil\r\n        $q = $db->prepare(\'UPDATE users \r\n        SET name = :name, city = :city, country = :country, \r\n            sex = :sex, twitter = :twitter, github = :github, \r\n            available_for_hire = :available_for_hire, bio = :bio \r\n            WHERE id = :id\');\r\n        $q->execute([\r\n            \'name\'               => $_POST[\'name\'],\r\n            \'city\'               => $_POST[\'city\'],\r\n            \'country\'            => $_POST[\'country\'],\r\n            \'sex\'                => $_POST[\'sex\'],\r\n            \'twitter\'            => $_POST[\'twitter\'],\r\n            \'github\'             => $_POST[\'github\'],\r\n            \'available_for_hire\' => !empty($_POST[\'available_for_hire\']) ? \'1\' : \'0\',\r\n            \'bio\'                => $_POST[\'bio\'],\r\n            \'id\'                 => get_session(\'user_id\')\r\n        ]);'),
(2, 'if (!empty($_GET[\'id\']) && $_GET[\'id\'] === get_session(\'user_id\')) {\r\n    //recuperer les infos d\'user en bdd\r\n    $user = find_user_by_id($_GET[\'id\']);\r\n\r\n    if (!$user) {\r\n        redirect(\'index.php\');\r\n    }\r\n} else {\r\n    redirect(\'profile.php?id=\' . get_session(\'user_id\'));\r\n}\r\n\r\nif (isset($_POST[\'update\'])) {\r\n    //Si tous les champs ont Ã©tÃ© complÃ©tÃ©s\r\n    if (not_empty([\'name\', \'city\', \'country\', \'sex\', \'bio\'])) {\r\n        $errors = [];\r\n\r\n        extract($_POST);\r\n\r\n        //mise Ã  jour du profil\r\n        $q = $db->prepare(\'UPDATE users \r\n        SET name = :name, city = :city, country = :country, \r\n            sex = :sex, twitter = :twitter, github = :github, \r\n            available_for_hire = :available_for_hire, bio = :bio \r\n            WHERE id = :id\');\r\n        $q->execute([\r\n            \'name\'               => $_POST[\'name\'],\r\n            \'city\'               => $_POST[\'city\'],\r\n            \'country\'            => $_POST[\'country\'],\r\n            \'sex\'                => $_POST[\'sex\'],\r\n            \'twitter\'            => $_POST[\'twitter\'],\r\n            \'github\'             => $_POST[\'github\'],\r\n            \'available_for_hire\' => !empty($_POST[\'available_for_hire\']) ? \'1\' : \'0\',\r\n            \'bio\'                => $_POST[\'bio\'],\r\n            \'id\'                 => get_session(\'user_id\')\r\n        ]);');

-- --------------------------------------------------------

--
-- Structure de la table `microposts`
--

DROP TABLE IF EXISTS `microposts`;
CREATE TABLE IF NOT EXISTS `microposts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content` longtext NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `user_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`),
  KEY `fk_post_user1_idx` (`user_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `microposts`
--

INSERT INTO `microposts` (`id`, `content`, `created_at`, `user_id`) VALUES
(1, 'Le groupe AT&amp;T pourrait céder la part de la société Hulu qu\'il détient via sa filiale WarnerMedia, ce qui pourrait précipiter le rachat définitif par Disney du spécialiste de la VoD.\r\n&lt;p&gt;Alors que Disney va lancer sa plateforme de streaming dans les prochains mois et que la firme américaine est sur le point de finaliser le rachat de la Fox, la société pourrait voir ses chances d\'avaler Hulu grandir assez rapidement. C\'est lors d\'une conférence téléphonique donnée par des représentants de AT&amp;T (qui possède une part minoritaire de Hulu) jeudi dernier que The Walt Disney Company a pu apprendre la bonne nouvelle.\r\nLa dette qui plombe AT&amp;T pourrait aider Disney.\r\nIl y a quelques jours, comme le rapporte The Information, le groupe AT&amp;T a annoncé qu\'il « envisageait de vendre sa participation de 10 % dans Hulu dans le cadre d\'une analyse d\'actifs plus large visant à  réduire sa dette ». Pour ne pas être trop perdu, faisons un bref rappel de la composition du capital du concurrent de Netflix. Comcast, la Fox et Disney détiennent chacun 30 % du capital de Hulu. Les 10 % restants appartiennent à  WarnerMedia, filiale de AT&amp;T.\r\n', '2019-08-24 00:00:00', 1),
(2, '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', '2019-08-24 10:42:00', 2),
(3, 'Le groupe AT&T pourrait céder la part de la société Hulu qu\'il détient via sa filiale WarnerMedia, ce qui pourrait précipiter le rachat définitif par Disney du spécialiste de la VoD.\r\n<p>Alors que Disney va lancer sa plateforme de streaming dans les prochains mois et que la firme américaine est sur le point de finaliser le rachat de la Fox, la société pourrait voir ses chances d\'avaler Hulu grandir assez rapidement. C\'est lors d\'une conférence téléphonique donnée par des représentants de AT&T (qui possède une part minoritaire de Hulu) jeudi dernier que The Walt Disney Company a pu apprendre la bonne nouvelle.\r\nLa dette qui plombe AT&T pourrait aider Disney.\r\nIl y a quelques jours, comme le rapporte The Information, le groupe AT&T a annoncé qu\'il « envisageait de vendre sa participation de 10 % dans Hulu dans le cadre d\'une analyse d\'actifs plus large visant à  réduire sa dette ». Pour ne pas être trop perdu, faisons un bref rappel de la composition du capital du concurrent de Netflix. Comcast, la Fox et Disney détiennent chacun 30 % du capital de Hulu. Les 10 % restants appartiennent à  WarnerMedia, filiale de AT&T.\r\n', '2019-08-24 00:00:00', 1),
(4, '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', '2019-08-24 10:42:00', 2),
(5, 'Le groupe AT&T pourrait céder la part de la société Hulu qu\'il détient via sa filiale WarnerMedia, ce qui pourrait précipiter le rachat définitif par Disney du spécialiste de la VoD.\r\n<p>Alors que Disney va lancer sa plateforme de streaming dans les prochains mois et que la firme américaine est sur le point de finaliser le rachat de la Fox, la société pourrait voir ses chances d\'avaler Hulu grandir assez rapidement. C\'est lors d\'une conférence téléphonique donnée par des représentants de AT&T (qui possède une part minoritaire de Hulu) jeudi dernier que The Walt Disney Company a pu apprendre la bonne nouvelle.\r\nLa dette qui plombe AT&T pourrait aider Disney.\r\nIl y a quelques jours, comme le rapporte The Information, le groupe AT&T a annoncé qu\'il « envisageait de vendre sa participation de 10 % dans Hulu dans le cadre d\'une analyse d\'actifs plus large visant à  réduire sa dette ». Pour ne pas être trop perdu, faisons un bref rappel de la composition du capital du concurrent de Netflix. Comcast, la Fox et Disney détiennent chacun 30 % du capital de Hulu. Les 10 % restants appartiennent à  WarnerMedia, filiale de AT&T.\r\n', '2019-08-25 00:00:00', 1),
(6, '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', '2019-08-25 00:00:00', 2),
(8, '\"La finalisation de l\'achat des actifs de Fox par Disney donnera déjà  le contrôle de Hulu à  Mickey, qui n\'en demandait pas tant lorsqu\'il a aussi appris que Comcast pourrait être poussé à  céder ses parts, refusant de rester dans une position minoritaire. Alors, s\'il s\'avère que AT&T veut bel et bien là¢cher Hulu, il faut maintenant se demander à  quel prix. En effet, depuis sa montée au capital en 2016 et après un investissement ultérieur, Warner a dépensé 800 millions de dollars dans Hulu.\r\nHulu dans le giron de Disney : un danger pour Netflix,\r\nSelon les médias américains, un récent document réglementaire indiquerait que Warner peut remettre sa participation à  Hulu à  tout moment jusqu\'au mois d\'aoà»t de l\'année prochain, sous certaines conditions. Reste à  savoir maintenant si la dette revendiquée par AT&T (après avoir racheté Time Warner pour 84,5 milliards de dollars) pourrait être suffisante pour satisfaire à  ces « certaines conditions ». A défaut, AT&T n\'aura pas l\'avantage dans les négociations.\"\r\n', '2019-08-25 00:00:00', 2),
(9, 'je publie un micropost', '2020-01-14 22:14:18', 1),
(10, 'et j\'en publie un deuxiÃ¨me pour Ãªtre sure\r\n', '2020-01-14 22:14:44', 1);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pseudo` varchar(24) NOT NULL,
  `email` varchar(96) NOT NULL,
  `password` varchar(128) NOT NULL,
  `active` enum('0','1') DEFAULT '0',
  `name` varchar(50) NOT NULL,
  `sex` enum('F','H') DEFAULT 'F',
  `city` varchar(50) DEFAULT NULL,
  `country` varchar(50) DEFAULT NULL,
  `twitter` varchar(50) DEFAULT NULL,
  `github` varchar(50) DEFAULT NULL,
  `available_for_hire` enum('0','1') DEFAULT '0',
  `bio` text DEFAULT NULL,
  `avatar` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `update_time` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `user_UNIQUE` (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `username_UNIQUE` (`pseudo`) USING BTREE,
  KEY `password_UNIQUE` (`password`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=52 DEFAULT CHARSET=utf8;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `pseudo`, `email`, `password`, `active`, `name`, `sex`, `city`, `country`, `twitter`, `github`, `available_for_hire`, `bio`, `avatar`, `created_at`, `update_time`) VALUES
(1, 'Lavande', 'sosso.boucher@gmail.com', '$2y$10$H1e..EN4MtZBls04JB1oGuGgf6yO54WzSnu3jvjKMQrLuD0PoBM06', '1', 'FrÃ©dÃ©rique Bougnoux', 'F', 'CartelÃ¨gue', 'France', '', 'opcr 2018', '1', 'je suis amoureuse de la commande en ligne et de ì†Œ ì§€ì„­ !', '/uploads/1/3807087b71e9f2a82111f5f5c076469f.jpg', '2020-01-14 21:51:13', '2020-01-14 21:51:13'),
(2, 'rfritsch', 'akutch@yahoo.com', '$2y$10$q8SMXuhWiSS3XZwwkmYbqOebU39IxBggBkHumltsSgQBSzXgwmvx2', '1', 'Johnpaul Fritsch DDS', 'F', 'Heidenreichton', 'Cyprus', NULL, NULL, '1', 'Sed ducimus sunt laborum et. Dolore dolor sint ipsam facilis maxime autem porro. Accusamus tempore occaecati sed beatae est ut dolor. Consequatur non ab omnis sint.', NULL, '1985-03-18 07:25:05', '2020-01-14 22:17:28'),
(3, 'kmccullough', 'shaylee.kovacek@hotmail.com', '$2y$10$cK91jOsiszj5ui8EZ0dgGeXEmLb0dPfD0n34265HuYcQZhO117GL.', '1', 'Miss Rylee Fritsch PhD', 'F', 'New Roman', 'Lao People\'s Democratic Republic', NULL, NULL, '0', 'Dicta architecto possimus labore voluptas corporis. Ea distinctio consequatur non eaque possimus sint sit. Neque nesciunt et maiores nemo ratione in. Facere ea cumque dolore aspernatur provident quos.', NULL, '1988-06-25 18:04:25', '2020-01-14 22:17:29'),
(4, 'jordy61', 'zoie51@yahoo.com', '$2y$10$rM3o2rhXxR00EsE3Rjoyg.Wr2q7eFBPkqTw5AeL.Vhov.T6v6RuL6', '1', 'Melody Gerhold', 'H', 'Patrickton', 'Zambia', NULL, NULL, '0', 'Debitis non a veritatis corporis quod. Perspiciatis doloremque facere quo atque modi iusto. Eum facilis ex exercitationem totam doloribus. Molestiae quia ea eveniet molestiae.', NULL, '1987-09-12 09:26:02', '2020-01-14 22:17:29'),
(5, 'hcrist', 'sandrine49@yundt.com', '$2y$10$hT6wTyLj9GwTtCARJWvt8eV2a8inkFvIN/7GOqJS3Q3AL9TyhV7Fi', '1', 'Miss Audra Hilpert', 'F', 'Smithambury', 'Saint Vincent and the Grenadines', NULL, NULL, '0', 'Quis unde iusto illo. Reprehenderit dolores magnam vel modi autem repellendus. Dignissimos illum numquam omnis debitis eos voluptatem.', NULL, '1997-06-12 19:16:52', '2020-01-14 22:17:29'),
(6, 'mayer.samantha', 'jamil.wolf@yahoo.com', '$2y$10$UQgKcTeAHeGo987asJaC0u7fZryi33KIvb6t8HjI35Tje/uILfhEC', '1', 'Vilma Bailey IV', 'F', 'Bergstromstad', 'Bouvet Island (Bouvetoya)', NULL, NULL, '0', 'Nemo cumque assumenda velit veniam animi quis. Sit ullam earum magni debitis corporis. Aut sed odio in culpa quas. Quo iste rem veritatis ex voluptate.', NULL, '1981-05-30 19:27:51', '2020-01-14 22:17:29'),
(7, 'cmurray', 'cnicolas@hotmail.com', '$2y$10$voKu.wfh3A9Y6Kz4rYZNqO.EDwxdqfHaDKpUOub.UDd7T0pQM4eFW', '1', 'Prof. Mylene Kertzmann V', 'F', 'Lake Floriantown', 'Oman', NULL, NULL, '1', 'Aut aperiam ut velit odit quae labore et aut. Ut enim natus perferendis maxime. Dolores officiis tempore temporibus blanditiis omnis qui maiores.', NULL, '1974-04-06 08:02:11', '2020-01-14 22:17:29'),
(8, 'forest10', 'savannah.schaden@hotmail.com', '$2y$10$ZvWWOprufvg0VUv3Fy1UFeJ2nyeo1d0dBoMLRRcSzP3VPZEFwnd1S', '1', 'Elenora Jerde', 'F', 'Gerhardshire', 'Iraq', NULL, NULL, '0', 'Voluptas ea consequatur sint odio ea. Sit magnam voluptatem ratione corporis qui omnis quibusdam. Reiciendis nam nobis cupiditate est magni excepturi praesentium. Est tempora sunt nesciunt rem.', NULL, '1983-12-27 18:38:52', '2020-01-14 22:17:29'),
(9, 'amely93', 'qmayert@runte.com', '$2y$10$QIY/geYRtP.bpkCdtpUZc.GL/ADTiB.CyU2NrQqFfPbXklDhjQRLK', '1', 'Julius Dach', 'F', 'Port Missouriburgh', 'Somalia', NULL, NULL, '1', 'Nemo ullam quas quod molestiae. Voluptatibus amet dolores autem deleniti optio modi. Qui perferendis mollitia iusto quidem. Ducimus in veritatis doloribus est voluptas assumenda.', NULL, '1986-06-02 19:14:14', '2020-01-14 22:17:29'),
(10, 'teresa.fay', 'nelda.deckow@smith.com', '$2y$10$pfiidK0qDdFl0VwLth6HMu4Hbj6VO1.Ein/613XLqhmQi1hn6u4Ka', '1', 'Prof. Dandre Homenick', 'H', 'Lake Rodside', 'Timor-Leste', NULL, NULL, '1', 'Sed veritatis aliquid praesentium omnis excepturi. Modi beatae est nesciunt vitae modi. Hic consequatur quos impedit cupiditate.', NULL, '1986-03-04 14:33:48', '2020-01-14 22:17:29'),
(11, 'kihn.miguel', 'vhessel@yahoo.com', '$2y$10$zFvkxdqunrxinKKpFiCiCe/ON/hoI86a9YGGWHjIo/vx9aj1Izuau', '1', 'Samara Mayert MD', 'H', 'Bergstromchester', 'Bahamas', NULL, NULL, '1', 'Porro dolores et quia possimus aspernatur dolorem fuga. Consequatur ex distinctio cum vel rerum quia cupiditate pariatur. Excepturi laudantium inventore excepturi vero impedit provident est minima. Doloremque nulla ut non et architecto.', NULL, '1996-07-01 04:05:48', '2020-01-14 22:17:29'),
(12, 'casper.brionna', 'alex.kiehn@walter.org', '$2y$10$XSDdFrdoRkEvtPWmv5A66uPiXnA1uxqwhPmPjZ7mwiPhpus1tEtlW', '1', 'Lizzie Ryan', 'F', 'Hudsonbury', 'Belgium', NULL, NULL, '0', 'Et ducimus rerum at cupiditate corrupti sequi at. Debitis fuga corrupti aut explicabo aliquam dolores sequi. Delectus et placeat quos error et quia. Dolore nihil consequatur est.', NULL, '1998-08-19 18:38:25', '2020-01-14 22:17:29'),
(13, 'jimmie.waters', 'wilkinson.veronica@nikolaus.net', '$2y$10$UfgdYPlzHkl6ExAABSDMEuZM95ydK6dStZKG2CqgTbW2dKDw/895O', '1', 'Clovis Kunde Jr.', 'H', 'Jerdeshire', 'Kuwait', NULL, NULL, '1', 'Qui voluptas ab id porro. Cumque non debitis sit eos. Quia non explicabo pariatur enim est at est quae.', NULL, '2003-11-24 11:58:04', '2020-01-14 22:17:29'),
(14, 'mcglynn.shaniya', 'gracie73@christiansen.org', '$2y$10$a.Pan6Q3hdU5phoUcmiYLee1gJc8mdhd8ZmL9Ns2O4ff25ReVhlqa', '1', 'Leon Jacobson', 'F', 'North Rolando', 'Egypt', NULL, NULL, '0', 'Repellat in eum aut soluta eos aut. Necessitatibus nihil aliquam minus facilis consectetur aut. At rem beatae ipsum quia. Impedit odit voluptatibus commodi distinctio nulla voluptas eveniet.', NULL, '1992-12-20 15:13:14', '2020-01-14 22:17:29'),
(15, 'toy.hane', 'price.efren@rath.biz', '$2y$10$RcP0qS7EMRiDLMSwyMgkmuIIuZehvSilNcPuxR413PeSuP.Ju12PK', '1', 'Aurore Lang', 'F', 'Baileychester', 'China', NULL, NULL, '0', 'Consequatur a qui deleniti consequatur quidem qui. Quibusdam repudiandae aspernatur velit. Sequi et cum laboriosam fugit. Alias accusamus dicta nam qui odio aut aliquam in.', NULL, '1982-06-22 14:23:19', '2020-01-14 22:17:29'),
(16, 'peyton.douglas', 'pwest@gmail.com', '$2y$10$qkaJ9uS0iLRyoIbPiV9F9eXSA8ZO1alZj4uLsUtz2FbEajVaR78qu', '1', 'Jimmy Beer PhD', 'F', 'Mullerview', 'Seychelles', NULL, NULL, '0', 'Voluptas reiciendis sequi consequuntur qui sunt totam et. Fugit pariatur voluptates recusandae dicta similique cupiditate. Consequatur pariatur officiis sequi eveniet qui quis voluptatem. Esse suscipit velit harum ullam.', NULL, '1971-12-20 18:49:57', '2020-01-14 22:17:29'),
(17, 'block.percival', 'owen96@ryan.com', '$2y$10$vV8xDWbXbDyCfhnfjkFpDe24h6pElEhJAS1N/G7RhCJ2ZrXM8Ei.2', '1', 'Emmanuel Legros II', 'F', 'Odiefurt', 'Cayman Islands', NULL, NULL, '1', 'Est consequatur occaecati vero esse. Quibusdam culpa rerum et necessitatibus dolorum. Ducimus modi ullam eligendi sed. Quaerat esse quidem occaecati et.', NULL, '2009-09-23 18:56:24', '2020-01-14 22:17:29'),
(18, 'dalton95', 'mollie.jones@schultz.biz', '$2y$10$9naarJshwFSWxYZ4l3iu9uX55uAE7vDw5hXEjxg6ltxhZ.mhnkF62', '1', 'Hortense Jaskolski', 'H', 'Lake Percival', 'Azerbaijan', NULL, NULL, '0', 'Facere adipisci et illum facere qui consectetur. Laudantium distinctio aut molestiae. Quis quod architecto et ut quo dolores non.', NULL, '1996-03-23 07:48:59', '2020-01-14 22:17:30'),
(19, 'mayert.armani', 'matilde09@hotmail.com', '$2y$10$Dl6LB2yJ5w7Fal8URnim6e2zWu/FfoFzl4lswjQet6g4YkbaDr9.a', '1', 'Annalise Von', 'F', 'North Leonard', 'Malawi', NULL, NULL, '1', 'Ut nesciunt perspiciatis atque sed dolores voluptatum ab. Vel nisi enim sit possimus quia error ad. Atque itaque nemo omnis rerum ratione nisi et. Et molestiae quia non rerum non esse. Non recusandae ducimus deserunt quia velit iusto dicta.', NULL, '1980-02-14 09:44:08', '2020-01-14 22:17:30'),
(20, 'jamey.medhurst', 'flossie.schamberger@hotmail.com', '$2y$10$7Kwl0QYnbDbJppYSYCfLweGU89cpfOZ0tZdF6sEkdgA9PnNF19cQG', '1', 'Koby Carroll', 'H', 'North Dulcefurt', 'Ethiopia', NULL, NULL, '0', 'Distinctio blanditiis ipsa quis officiis aspernatur voluptatem quos. Expedita quod repudiandae et velit dolores similique temporibus. Corporis et et molestiae et velit dolores nostrum qui. Minima impedit qui sed.', NULL, '2016-05-04 18:09:14', '2020-01-14 22:17:30'),
(21, 'sheller', 'mjast@simonis.com', '$2y$10$KMbb/Ca1EZyhqDzCaohr2uONzdwORoriTYy.BDbqgK0ANOO1e6Vwy', '1', 'Mr. Tracey Roob Sr.', 'F', 'Jaceychester', 'South Africa', NULL, NULL, '0', 'Harum eum omnis aliquam. Similique officia ea hic et quis. Earum iure officia vel assumenda dolor.', NULL, '2005-08-09 01:36:18', '2020-01-14 22:17:30'),
(22, 'victoria.white', 'una44@kunde.biz', '$2y$10$OQc.WcjrN9JzZZAffgPA4envt/BhaT3HwlFXKngUKDhJ1Jxm7Q.2e', '1', 'Clay Wehner', 'H', 'Dayneberg', 'Pakistan', NULL, NULL, '0', 'Et quia quas rerum deleniti vel reprehenderit. Eum neque sint voluptas sunt suscipit nihil. Omnis ducimus ducimus soluta mollitia exercitationem aut temporibus. Velit voluptas quo repudiandae.', NULL, '2008-02-02 05:50:11', '2020-01-14 22:17:30'),
(23, 'summer08', 'dwalter@schoen.com', '$2y$10$c58anrUYRIdTKBpOPV/Rhen5rN9JtzYHS9HqmOnmcr1af/inVZr16', '1', 'Marc Tromp', 'H', 'Dagmarstad', 'American Samoa', NULL, NULL, '0', 'Quo minus blanditiis rerum consequuntur. Vitae porro recusandae dolores quis necessitatibus sunt. Aliquid id aut quia non cumque.', NULL, '2019-03-26 03:24:43', '2020-01-14 22:17:30'),
(24, 'beverly77', 'halvorson.petra@hotmail.com', '$2y$10$vT0M9SAPiXPj8O6DdEjD5enIpGeYFZlcai3b2e.J6iebcYOqSeV0W', '1', 'Miss Alberta Mraz DVM', 'F', 'Odaville', 'Saudi Arabia', NULL, NULL, '1', 'Blanditiis delectus omnis rerum ratione nisi. Mollitia fuga aut similique consequatur voluptas. Rerum voluptatem natus omnis sunt excepturi.', NULL, '1991-08-19 14:10:58', '2020-01-14 22:17:30'),
(25, 'alvis.towne', 'blanda.kaycee@prohaska.net', '$2y$10$iRtndVihAfJZ49r4ety8hutAYOzs5R5.uDEuXfz5VqBz8wdNrpx8q', '1', 'Francis Buckridge', 'H', 'Millsport', 'Mozambique', NULL, NULL, '1', 'Rerum non commodi neque non porro tempora cupiditate. Fugiat tempora et doloremque veritatis. Harum eaque omnis nam aspernatur et. Iste rem aut omnis dolore explicabo quod.', NULL, '1996-06-16 23:00:36', '2020-01-14 22:17:30'),
(26, 'hammes.cristina', 'mckenzie.karlie@hotmail.com', '$2y$10$JU/8.CTWfP0Gz0RCwnkdeuVYmQbXbjrjooEMkTULKnzw/dvR5Udte', '1', 'Dariana Blanda Jr.', 'F', 'South Yasmeen', 'Nepal', NULL, NULL, '0', 'Dignissimos ut culpa fuga iure. Voluptates magnam nemo sed. Veritatis iusto est minus sapiente odit.', NULL, '2000-07-09 09:30:12', '2020-01-14 22:17:30'),
(27, 'wrice', 'katarina79@lind.biz', '$2y$10$M94aMdKSfcpGORddk5vgpOvdf6m3PA0vjSXAN7dYAZOfZuKHrVFJS', '1', 'Felix Mertz', 'F', 'Farrellhaven', 'French Southern Territories', NULL, NULL, '0', 'Molestiae nobis neque ut eveniet exercitationem rerum corporis. Nesciunt incidunt eos maiores tempora nulla molestiae repellendus.', NULL, '1979-08-03 11:33:43', '2020-01-14 22:17:30'),
(28, 'strosin.aleen', 'kreiger.dante@hoppe.biz', '$2y$10$ZGBWtNPS9.1BPgWblh.kVO5KPTufq.act.bSgQCCHX9jGK5cHpESa', '1', 'Flo Leuschke', 'F', 'West Andreane', 'Serbia', NULL, NULL, '0', 'Vel ex fugiat minima exercitationem. Sit magni et ea dolor. Ut commodi dolores est molestiae amet molestias.', NULL, '1993-08-23 04:21:02', '2020-01-14 22:17:30'),
(29, 'lkilback', 'stamm.myrtle@yahoo.com', '$2y$10$ZbYk6Sf3kiyO1dIRzS0/AOMjNgicdM64N0MkCN1kQ4odXwcrz7w5i', '1', 'Roman Tromp', 'F', 'New Erik', 'Cocos (Keeling) Islands', NULL, NULL, '0', 'Sit laudantium architecto quas. Doloribus odio quia et fugiat. Nostrum praesentium eos temporibus porro eveniet libero.', NULL, '2000-11-23 05:28:47', '2020-01-14 22:17:30'),
(30, 'dickinson.cameron', 'xdenesik@conroy.com', '$2y$10$Un8OTHB3Lc7gZ58iKHsVcOmMNW9KuaL8Z0EM0XylJb41NmqFmgMye', '1', 'Melvina Hilpert', 'F', 'Kubmouth', 'Russian Federation', NULL, NULL, '0', 'Ratione est omnis quia ad. Commodi mollitia rerum doloremque repellendus enim sequi eaque. Ut repudiandae dolorum sit earum nesciunt distinctio. Nisi veritatis explicabo ea maxime. Sed dolor recusandae saepe a.', NULL, '1979-12-17 22:06:42', '2020-01-14 22:17:30'),
(31, 'klocko.earlene', 'nhuels@stiedemann.biz', '$2y$10$DW9jcWXTLkDSVHSmGmHuHeFAmM2E1dtIKPM5peu0WvK2i45D8ayKq', '1', 'Miss Estella Lebsack III', 'F', 'North Yolandaland', 'Cambodia', NULL, NULL, '1', 'Quidem et aut quis ut in sit modi omnis. Ea dolores ad aperiam sit aperiam doloremque repudiandae. Eum odio in in doloribus. Odio nesciunt sit similique vitae.', NULL, '1973-02-23 06:04:53', '2020-01-14 22:17:30'),
(32, 'kody.rempel', 'upton.candace@hotmail.com', '$2y$10$FzNJZ1U/1xyQ1jZpRtm1GebbLjENCXQOz7DS38kdOohNIsutZI2eK', '1', 'Jewell O\'Hara', 'F', 'Blickview', 'Argentina', NULL, NULL, '0', 'Iusto labore et rerum suscipit. Molestias quibusdam rerum dolores ea pariatur. Ut fuga aut quia non. Quia consectetur pariatur consequatur aut omnis deleniti minus consequatur.', NULL, '1980-02-22 19:45:20', '2020-01-14 22:17:30'),
(33, 'virgie.heaney', 'gladys.schuster@johnson.biz', '$2y$10$TpY6CC98fyuGi8b74/npjepU0p15haEdZ42zvEW1Yukc4H.P/2kzC', '1', 'Johan Schumm', 'H', 'East Janetstad', 'Vietnam', NULL, NULL, '0', 'Odio quo fugit sint repudiandae esse. Iste sed optio qui. Numquam aut recusandae magnam tenetur inventore nesciunt quia.', NULL, '1992-02-27 19:30:11', '2020-01-14 22:17:31'),
(34, 'gideon59', 'rparisian@klein.com', '$2y$10$PyblHCc3G.mv6ONtN7lcdO8LiZQWh7e3GnwmtsiSV8uTAFUHIc2qq', '1', 'Miss Linda Boyle', 'H', 'North Ulises', 'Mongolia', NULL, NULL, '0', 'Asperiores dolore nobis totam nisi. Mollitia id molestiae occaecati eos architecto natus. Cum itaque ut voluptatum sint animi qui. Nulla sit aut suscipit fuga officiis ullam fugiat.', NULL, '1974-09-30 02:15:12', '2020-01-14 22:17:31'),
(35, 'letitia.lueilwitz', 'qdooley@aufderhar.com', '$2y$10$3NUK5cNl3AnkKA.xIbreG.enY5n6ji.EMP1NIuhJ8l1wOZCdoARm6', '1', 'Casimir Larson', 'F', 'Johnnybury', 'Albania', NULL, NULL, '1', 'Natus delectus laboriosam voluptatem at. Nostrum non omnis provident eius tenetur fugit porro in. Quae fugit est exercitationem.', NULL, '1993-07-03 14:55:47', '2020-01-14 22:17:31'),
(36, 'evelyn26', 'jamel72@gmail.com', '$2y$10$yoqZXKI9b.jGUb8WFtVM3.kH9gAvb5o2H1qHyn/sLG6rzK8QNTmTy', '1', 'Ms. Anita Casper', 'F', 'East Lysanne', 'Belarus', NULL, NULL, '0', 'Debitis dolor neque est ullam aut voluptates maiores. Sit saepe laboriosam animi sit deserunt doloribus ut repellat. Itaque aut deleniti perspiciatis non et sint rerum. Corporis aspernatur sapiente perferendis.', NULL, '1998-12-02 06:39:19', '2020-01-14 22:17:31'),
(37, 'hudson.maxie', 'kacie67@franecki.info', '$2y$10$zyLi5V6MzWKbtPdrbXemyuNk9K5QrKJTn07kp/SbcSaK05cujIXiS', '1', 'Michelle Mayert', 'F', 'Wardshire', 'Finland', NULL, NULL, '1', 'Incidunt adipisci et pariatur ex explicabo dolorem. Quia consequatur mollitia quos est quis sed sint. Temporibus quia ab explicabo aut voluptatem quis exercitationem optio.', NULL, '2002-04-12 07:08:00', '2020-01-14 22:17:31'),
(38, 'nyasia77', 'jwilkinson@yahoo.com', '$2y$10$.v2meqA1.CRlo4a9JzKVZ.RcpQDfV.Y1dBQhRPXYl4KUTeNNsv3o.', '1', 'Rylan Schultz', 'H', 'Lake Pietro', 'Uruguay', NULL, NULL, '0', 'Officiis tenetur excepturi voluptatem qui nesciunt explicabo molestiae. Voluptatem id ipsum quo harum et velit est atque. Quis modi est similique qui aut quod.', NULL, '1979-04-25 23:30:42', '2020-01-14 22:17:31'),
(39, 'aubrey.bartell', 'javon32@satterfield.com', '$2y$10$JsEn//OV76cGdSvfjW.Kme3O.nERZmYuR4itKCq57GE5qHc6DX7AG', '1', 'Mr. Lamont Harris', 'F', 'West Chase', 'Mauritius', NULL, NULL, '0', 'Debitis cumque nihil velit id. Natus tenetur ut inventore aliquid libero praesentium. Quia velit est sint ea sint.', NULL, '1994-06-22 05:40:08', '2020-01-14 22:17:31'),
(40, 'pweimann', 'kacie19@hotmail.com', '$2y$10$8IkLMAZY2mzyQPB6.zi08uC7mWW2Sxhf/Iprad0NaNEbcbx7yxKmW', '1', 'Hillary Yost', 'H', 'South Jaymeville', 'Gibraltar', NULL, NULL, '0', 'Ut possimus quibusdam consectetur natus occaecati. Veniam totam facere harum aspernatur. Nulla nesciunt aut odio tempora aut nemo. Aut ipsam facere iure aut sit et aut.', NULL, '1985-10-28 05:05:44', '2020-01-14 22:17:31'),
(41, 'strosin.abelardo', 'marley.morissette@labadie.com', '$2y$10$OF98U39kDxeCEiboFs1MvOXpwtsuZGRopZJOSpEr2k6W4Xf4Qu1ku', '1', 'Olen Koch', 'H', 'New Benjamin', 'Macao', NULL, NULL, '1', 'Consequatur qui repudiandae vel ratione cupiditate. Ea corporis est veritatis id cupiditate vel debitis. Et reiciendis aut molestiae molestiae sequi cumque pariatur. Ducimus magnam eius reprehenderit qui.', NULL, '2018-01-26 11:02:20', '2020-01-14 22:17:31'),
(42, 'jarod.bradtke', 'gsenger@jast.com', '$2y$10$xGKUJXE6MkHCIrRTjL1Y.On3oC5VZzxWbbbiESsq6O9bcGfRmWFSm', '1', 'Ayla Spencer', 'H', 'Schroederborough', 'Syrian Arab Republic', NULL, NULL, '1', 'Sit quos qui magnam. Saepe sed aliquam non sed. Ut occaecati necessitatibus libero. Tempora ipsum quasi et incidunt qui.', NULL, '1991-02-15 16:11:24', '2020-01-14 22:17:31'),
(43, 'lbalistreri', 'dustin30@hotmail.com', '$2y$10$kD6a67w4eZRmTLULWZta8utYGzeJ1js3074.u3/e6kCZ.Udghr5je', '1', 'Jadyn Grady Jr.', 'F', 'Padbergtown', 'Christmas Island', NULL, NULL, '0', 'Deleniti perferendis dolores enim ratione. Consequatur aut voluptas earum repudiandae et. Accusantium laudantium laudantium ratione.', NULL, '2014-12-29 01:09:42', '2020-01-14 22:17:31'),
(44, 'hritchie', 'bruce27@hotmail.com', '$2y$10$fBz2kidKrSL3v1k08Xj10e2IQXqgMb2o7.NtGCHS2t/H533PmB7sC', '1', 'Chelsie Steuber', 'H', 'East Claudiafort', 'Bolivia', NULL, NULL, '1', 'In error maiores totam quia dolorem aut nulla. Beatae omnis ea minus dignissimos. Est et deserunt ipsam.', NULL, '2019-10-03 13:09:22', '2020-01-14 22:17:31'),
(45, 'ortiz.bettye', 'jonathon12@hotmail.com', '$2y$10$Kgjnz9I1NMWBgXEW/.6Eq.fnRpLzB1TZTquufCLXucmOb5X96hDkS', '1', 'Ms. Katelyn Crooks Sr.', 'H', 'DuBuqueview', 'Colombia', NULL, NULL, '0', 'Quas et et distinctio doloremque. Voluptatem architecto similique beatae non voluptatem. Excepturi reiciendis ut provident nulla earum qui. Odit aut eaque molestias est quibusdam et magni.', NULL, '2019-08-27 15:35:41', '2020-01-14 22:17:31'),
(46, 'vidal.flatley', 'kyle.swaniawski@hirthe.com', '$2y$10$u5uf.W3x/RZLCIVvR86JluehOw9y7tkZ6eIGRKv/r3W2d18mMR/yy', '1', 'Mercedes Kling PhD', 'F', 'North Makaylafort', 'Philippines', NULL, NULL, '1', 'Quae doloribus aut id et consequatur nam corrupti. Perferendis officiis nulla amet voluptas totam beatae veritatis. Dolorem officia molestiae molestiae est placeat. Numquam id enim architecto sed. Alias occaecati et molestiae libero autem ipsum.', NULL, '1973-06-11 03:20:10', '2020-01-14 22:17:31'),
(47, 'emil03', 'bkoss@gmail.com', '$2y$10$UbIkAVD2FIefjMPiUg7u0e3.h6NvGGweax0yrSoiBpN5JTeGkrdYW', '1', 'Kendall Muller', 'F', 'Lake Kiana', 'Tokelau', NULL, NULL, '1', 'Quo nobis facere necessitatibus dolorum aliquid molestiae quae. Quo cumque cum dignissimos odio consequatur.', NULL, '1981-11-29 12:28:20', '2020-01-14 22:17:31'),
(48, 'dschaden', 'sage.price@dare.com', '$2y$10$eHvMlPIVt.ExHXw2RgNq.OTFAlxjTem0KKIEVxeZDwqLgoXmBiWb.', '1', 'Lucius Jakubowski DVM', 'F', 'Aleneton', 'Guadeloupe', NULL, NULL, '0', 'Dolores omnis id maxime aut dolorem laudantium. Tempore tempore saepe et necessitatibus vero impedit ut. Modi eos nihil quis suscipit laudantium ad fugit. Enim quis modi non nostrum sit enim provident illo. Rerum et quia ut eaque.', NULL, '1981-02-20 13:02:30', '2020-01-14 22:17:31'),
(49, 'zpouros', 'dorothea.dibbert@gibson.info', '$2y$10$FeciMt2GixcA1rfDOYEObeu7NfCqvdYGKumBe2P286wUAfY6vy/tG', '1', 'Prof. Nyah Rodriguez', 'H', 'Jordifort', 'Papua New Guinea', NULL, NULL, '1', 'Ea rerum enim minima. Libero suscipit sunt ipsum debitis iusto et. Ea esse sunt ratione aut.', NULL, '1999-05-27 16:16:35', '2020-01-14 22:17:32'),
(50, 'tbartell', 'marcus88@wilderman.com', '$2y$10$3kJ6MizO2zRbPgiSXLRDCO8funHQpqk4nBQgbySzcWR./pIG/LVhu', '1', 'Mr. Domenic Abbott', 'H', 'New Reannaport', 'Mexico', NULL, NULL, '0', 'Omnis a quo minus harum provident. Tempora quia nobis ratione sed qui. Odit aliquid nostrum voluptas voluptas non quo corrupti.', NULL, '2006-06-29 02:41:04', '2020-01-14 22:17:32'),
(51, 'winona.muller', 'pconroy@yahoo.com', '$2y$10$vUhQhxcDpXEbjTsQFye.G.Mb4G21qdJ.QDQVD12hz8yKhKWPqZ7Wq', '1', 'Miss Lucie Ziemann Jr.', 'H', 'Browntown', 'Norfolk Island', NULL, NULL, '0', 'Provident quisquam sit maiores unde. Sed quia minus deleniti repellendus temporibus blanditiis. Et voluptates officia autem ex nostrum. Ipsam rerum et corporis consequatur tempore.', NULL, '2002-03-12 07:49:43', '2020-01-14 22:17:32');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
